webdriver:
  browser: chrome
  headless: false
  firefox_profile: profile
  window:
    height: 0
    width: 0

timeouts:
  click_wait: 0.5
  event_wait: 0
  short: 8
  medium: 30
  long: 120
  canvas_poller: 60

cal_net:
  base_url: https://auth-test.berkeley.edu

suite_c:
  base_url: https://app-qa.ets-berkeley-suitec.net
  lti_key: secret
  lti_secret: secret
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  poller_retries: 10
  acceptable_events_diff: 0.03

canvas:
  base_url: https://ucberkeley.test.instructure.com
  admin_sub_account: secret
  uc_berkeley_sub_account: secret
  official_courses_sub_account: secret
  qa_sub_account: secret
  enrollment_retries: 20
  create_site_tool: secret
  course_add_user_tool: secret
  course_captures_tool: secret
  rosters_tool: secret
  official_sections_tool: secret
  mailing_lists_tool: secret
  mailing_list_tool: secret
  e_grades_export_tool: secret

junction:
  base_url: https://junction-qa.berkeley.edu
  basic_auth_password: secret
  admin_uid: secret

oec:
  term: 2018-B
  blue_project_title: 'Spring 2018 Evaluations'
  first_name: secret
  last_name: secret
  uid: secret
  sis_id: secret
  email: secret

users:
  super_admin_username: secret
  super_admin_password: secret
  super_admin_uid: secret
  ets_qa_username: secret
  ets_qa_password: secret
  test_user_password: secret
  oski_uid: secret

lrs:
  base_url: https://app-qa.ets-berkeley-cloudlrs.net
  lti_key: secret
  lti_secret: secret
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  script_loops: 10
  event_time_discrep_seconds: 2

boac:
  base_url: https://asc-pilot-qa.berkeley.edu
  password: secret
  term: Spring 2018
  current_scores_term: Fall 2017
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  tooltips: true
  loch_scores: true
  loch_assignments: false
  loch_page_views: false
