#### Browser driver configs ####

webdriver:
  browser: chrome
  headless: false
  chrome_profile: true
  firefox_profile: profile
  window:
    height: 0
    width: 0

timeouts:
  click_wait: 0.5
  event_wait: 0
  short: 8
  medium: 30
  long: 120
  canvas_poller: 60

#### Test user accounts ####

users:
  super_admin_username: secret
  super_admin_password: secret
  super_admin_uid: secret
  ets_qa_username: secret
  ets_qa_password: secret
  test_user_password: secret
  oski_uid: secret

#### Test environment configs ####

boac:
  base_url: https://asc-pilot-qa.berkeley.edu
  password: secret
  term: Summer 2018
  term_code: 2182
  analytics_term: Spring 2018
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  tooltips: true
  screenshots: true
  nessie_scores: true
  nessie_assignments: true
  nessie_last_activity: true
  test_dept: UWASC
  test_max_users: 10
  test_canvas_data_lag: 1
  test_team_assignments: GOM
  test_team_class_page: GOW
  test_team_curated_cohort: BAM
  test_team_last_activity: TNM
  test_team_search: TNW
  test_team_sis_data: FBM

cal_net:
  base_url: https://auth-test.berkeley.edu

canvas:
  base_url: https://ucberkeley.test.instructure.com
  admin_sub_account: secret
  uc_berkeley_sub_account: secret
  official_courses_sub_account: secret
  qa_sub_account: secret
  enrollment_retries: 20
  create_site_tool: secret
  course_add_user_tool: secret
  course_captures_tool: secret
  rosters_tool: secret
  official_sections_tool: secret
  mailing_lists_tool: secret
  mailing_list_tool: secret
  e_grades_export_tool: secret

junction:
  base_url: https://junction-qa.berkeley.edu
  basic_auth_password: secret
  admin_uid: secret

lrs:
  base_url: https://app-qa.ets-berkeley-cloudlrs.net
  lti_key: secret
  lti_secret: secret
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  script_loops: 10
  event_time_discrep_seconds: 2

nessie:
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  rds_host: secret
  rds_port: secret
  rds_name: secret
  rds_user: secret
  rds_password: secret

oec:
  term: 2018-C
  blue_project_title: 'Summer 2018 Evaluations'
  first_name: secret
  last_name: secret
  uid: secret
  sis_id: secret
  email: secret

salesforce:
  base_url: https://test.salesforce.com
  username: secret
  password: secret

suite_c:
  base_url: https://app-qa.ets-berkeley-suitec.net
  lti_key: secret
  lti_secret: secret
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  poller_retries: 10
  acceptable_events_diff: 0.03
