webdriver: firefox

timeouts:
  short: 8
  medium: 30
  long: 120

cal_net:
  base_url: https://auth-test.berkeley.edu

suite_c:
  base_url: https://calcentral-col-qa-01.ist.berkeley.edu
  lti_key: secret
  lti_secret: secret
  poller_retries: 20

canvas:
  base_url: https://ucberkeley.test.instructure.com
  admin_sub_account: secret
  official_courses_sub_account: secret
  qa_sub_account: secret
  create_site_tool: secret
  course_add_user_tool: secret
  course_captures_tool: secret
  rosters_tool: secret
  official_sections_tool: secret
  mailing_lists_tool: secret
  mailing_list_tool: secret
  e_grades_export_tool: secret

junction:
  base_url: https://junction-qa.berkeley.edu
  basic_auth_password: secret
  admin_uid: secret

users:
  super_admin_username: secret
  super_admin_password: secret
  super_admin_uid: secret
  ets_qa_username: secret
  ets_qa_password: secret
  test_user_password: secret
